### ISSUE TITLE
Slow read of large files

### ISSUE THREAD

**Issue by langley** [scaled/scaled#5]
Tried reading a large-ish text file; wc on linux tells me my journal file is " 34917  275306 1618675 journal"
This takes on the order of 15 seconds to load (on an Ubuntu 14.04 machine w/ a quad processor). For comparison, emacs does it in a second or less. 

editorial note: I LOVE THAT YOU ARE CREATING SCALED!!!! As a long time emacs user and huge Scala fan, I'm very excited about the possibilities! THANK YOU

**Comment by samskivert** [comment]
Yeah, I'm not doing anything very smart with regard to large files (yet). I basically read the whole file and line break it, and create some small objects for every line. I don't create UI stuff for a line until it's visible, but even the process of line breaking a 34k-line file probably takes a long time.

I can probably pretty easily create some standalone tests that just line break a file, then just create the LineImpl instances for each line, and at least get a better feel for what's slow.

I'm probably going to have to rework things to line break and create LineImpl on demand, but if I can get an order of magnitude improvement somewhere else, maybe I can push that grunt work off a big longer. :)

**Comment by langley** [comment]
Thanks for looking in to it. I may try and orient myself to the code base
over the weekend... but the "honey do" list may interfere with that.

**Comment by samskivert** [comment]
FWIW, I have made some improvements on this front and now I can load /usr/dict/words (a 992K file with 235k lines) in about two seconds from a cold start and about one second from a running editor.

It's still a little sluggish when switching to and from such a large buffer, so more improvements can be made. It seems to be linear in the number of lines in the file, so a 50k line file is about 4x faster. I'll try to keep improving this front, but I don't feel quite so bad about it now. :)
